from flask import Flask, render_template, request, jsonify, send_from_directory
from openai import OpenAI
import os
import base64
import uuid
from datetime import datetime
from dotenv import load_dotenv

ITEM_FOLDER = "item_images"   # Folder where each latest item image is stored
ALL_FOLDER = "all_images"     # (optional) where raw incoming images are saved


client = OpenAI(api_key=os.getenv("API_KEY"))
prompt = "Analyze the image only if it is sufficiently sharp and not blurry. If the image is blurry, out of focus, low-resolution, motion-blurred, or otherwise unclear, return an empty string. If the image is clear: detect only objects that humans commonly interact with in everyday life. Focus on items people touch, use, or manipulate, such as personal items, tools, household appliances, office objects, or frequently handled public objects. Ignore background scenery, walls, floors, plants, or furniture not intended for direct human use. If the image is blank, black, empty, or contains no human-interacted objects, return an empty string. Do not guess or hallucinate. Return a comma-separated list of detected objects, each appearing only once."
app = Flask(__name__)

def save_item_images(image_bytes: bytes, detected_items: list[str]):
    # --- 1. Save full image (optional, remove if you don't want a history) ---
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    image_id = f"{timestamp}_{uuid.uuid4().hex}.jpg"
    all_path = os.path.join(ALL_FOLDER, image_id)

    with open(all_path, "wb") as f:
        f.write(image_bytes)

    # --- 2. For each detected item, store only the latest image ---
    print(detected_items)
    for item in detected_items:
        # Convert "bottle" → "bottle.jpg"
        safe_name = item.strip().lower().replace(" ", "_") + ".jpg"
        item_path = os.path.join(ITEM_FOLDER, safe_name)

        # Overwrite the old file for this item (saves space)
        with open(item_path, "wb") as f:
            f.write(image_bytes)

    return {
        "saved_image": all_path,
        "updated_items": detected_items
    }
@app.route("/")
def index():
    return render_template("index.html") # Page with and capture button
@app.route("/item_images/<path:filename>")
def serve_item_image(filename):
    return send_from_directory(ITEM_FOLDER, filename)


@app.route("/analyze", methods=["POST"])
def analyze():
    file = request.files["image"]
    img_bytes = file.read()
    img_b64 = base64.b64encode(img_bytes).decode("utf-8")

    # Send image to GPT
    response = client.chat.completions.create(
        model="gpt-5-mini",
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {"type": "image_url",
                     "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}}
                ]
            }
        ]
    )

    raw_text = response.choices[0].message.content.strip()

    # Items in this frame
    if raw_text == "":
        detected_items = []
    else:
        detected_items = [x.strip() for x in raw_text.split(",") if x.strip()]

    # Save images
    save_item_images(img_bytes, detected_items)

    # -------------------------------------
    # Build ALL-TIME list from item_images/
    # -------------------------------------
    all_items_output = []
    for filename in os.listdir(ITEM_FOLDER):
        if filename.lower().endswith(".jpg"):
            label = filename.replace(".jpg", "").replace("_", " ")
            all_items_output.append({
                "label": label,
                "image": f"/item_images/{filename}"
            })

    # FRONTEND EXPECTS: items = [...]
    return jsonify({"items": all_items_output})


app.run(
    host="0.0.0.0",       # accessible from LAN
    port=5000,
    debug=True,
    ssl_context=(
        r"C:\Users\simon\PythonProject\Hackathon2025\cert.pem",
        r"C:\Users\simon\PythonProject\Hackathon2025\key.pem"
    ) # use the files generated by Git Bash
)